site_name: Truthy Docs
markdown_extensions:
  - pymdownx.keys
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  generator: false

theme:
  name: material
  favicon: fontawesome/solid/book

  icon:
    logo: fontawesome/solid/book

  features:
    - navigation.expandm
    - header.autohide
    - navigation.instant
    - content.tabs.link

  palette: 


    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 


        name: Switch to light mode
    - scheme: default 


      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css