site_name: Truthy Docs
markdown_extensions:
  - pymdownx.keys
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 

extra:
  generator: false

theme:
  name: material
  favicon: fontawesome/solid/book

  icon:
    logo: fontawesome/solid/book

  features:
    - navigation.expandm
    - header.autohide
    - content.tabs.link

  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css